export const typeStyles = {
  grass: { color: "🌿", bgColor: "#78C850" },
  fire: { color: "🔥", bgColor: "#F08030" },
  water: { color: "💧", bgColor: "#6890F0" },
  bug: { color: "🐛", bgColor: "#A8B820" },
  normal: { color: "⚪️", bgColor: "#A8A878" },
  electric: { color: "⚡️", bgColor: "#F8D030" },
  ground: { color: "🌍", bgColor: "#E0C068" },
  fairy: { color: "🧚", bgColor: "#EE99AC" },
  fighting: { color: "🥊", bgColor: "#C03028" },
  psychic: { color: "🔮", bgColor: "#F85888" },
  rock: { color: "🪨", bgColor: "#B8A038" },
  ghost: { color: "👻", bgColor: "#705898" },
  ice: { color: "❄️", bgColor: "#98D8D8" },
  dragon: { color: "🐉", bgColor: "#7038F8" },
  dark: { color: "🌑", bgColor: "#705848" },
  steel: { color: "⚙️", bgColor: "#B8B8D0" },
  poison: { color: "☠️", bgColor: "#A040A0" },
  flying: { color: "🕊️", bgColor: "#A890F0" },
};
